### ISSUE TITLE
__contains__() isn't working for test ???

### ISSUE THREAD

**Issue by nucle0tides** [QuantumFractal/Data-Structure-Zoo#7]
see test_contains_sucess. test fails when trying to see if singleLinkListData contains "Watson"

**Comment by DrNightmare** [comment]
This test fails because the ____contains____() method does not check the last item of a list.
The condition:
`while cur.next is not None:`
evaluates to false at the last before item, not the last item.

Editing this to:
`while cur is not None`
fixes this bug.

Also, the same method has an `else:` section which is almost never executed; the method fails to return `False` when an item is not present in the list; this is fixed by removing the line containing `else:` and just returning `False`.

**Comment by nucle0tides** [comment]
Thanks for working that one out!
